### ISSUE TITLE
Zoom snaps back on update

### ISSUE THREAD

**Issue by swordsteel** [perliedman/leaflet-realtime#13]
Would be nice to have this not happen, so when a gps tracker is moving and the user has zoomed in or out, the map doesn't snap back out or in to its default zoom level. Quite distracting. 

User needs to zoom in and follow at closer level of detail.

Currently any zoom by the user is undone when the update hits.

**Comment by perliedman** [comment]
This isn't related to the plugin, but rather how the example code is written. Look at the event listener for the `update` event:

```
realtime.on('update', function() {
    map.fitBounds(realtime.getBounds(), {maxZoom: 3});
});
```

Every time the data is updated, it will fit the map around the features, but with a maximum zoom of 3. If you want another behaviour, just change the event listener code.

**Comment by rohling** [comment]
Hello:
    I agree with the user: "dev-brother".  But, I can't fix the behaviour in code.   You could provide a tip?

**Comment by perliedman** [comment]
@rohling just guessing since I don't have your code, but you might have copied the example code, which does a call to `fitBounds`, which is why the map snaps to a certain zoom/location. If you don't want this behaviour, remove that call from the event listener.

Leaflet Realtime in itself doesn't modify the map's zoom or center, it's entirely handled by the using application.
