### ISSUE TITLE
Examples show blank maps

### ISSUE THREAD

**Issue by spaceneedle** [perliedman/leaflet-realtime#139]
I downloaded leaflet-realtime and put it into a directory accessible by apache2. I am using the most recent version of Chrome.

The pages serve okay, but going to earthquakes.html, trail.html, etc. results in a blank gray map. All I see are the zoom buttons. Loading earthquakes.html also shows a layers selector.

Am I doing anything wrong? Do the examples require additional modification to work or should it work out of the box?

I also do not see any javascript errors or network resources that are producing errors -- but its not fetching tiles either.

**Comment by sankthetester** [comment]
yes, I have observed the exact same thing although I've only tested on localhost and tried uploading the entire master repo to shared linux-based hosting provider service...

are we missing something obvious?

**Comment by perliedman** [comment]
Hi guys and thanks for the heads up,
this was an unfortunate regression from an otherwise sound PR i merged a while ago. Unfortunately I relied on my automated tests and code review rather than actually running the examples, so a small but very important breaking change snuck in there.

I have pushed a fix and released version 2.1.3 that contains this fix.
