### ISSUE TITLE
Adapting slightly different GeoJSON response from server

### ISSUE THREAD

**Issue by m-menon** [perliedman/leaflet-realtime#28]
hi,

Thanks a lot for the useful plugin. I have a small question. If the server returns GeoJSON as shown below what would be the best way to get leaflet-realtime to use it. I was wondering if I could transform or convert the url at the client side rather than the server as I have limited access to that

`{"resource":[{"_id":"5708b0627d57d0c20f3c989d","geojson":{"geometry":{"type":"Point","coordinates":[103.631185,1.311355]},"type":"Feature","properties":{"uniqueid":"359710043737114","address":"9 Tech Park Cres, Singapore, SG","speed":"0.0/0.0 (kph/mph)","datetime":"2016-04-09T07:33:52.000Z","fixtime":1460187232000,"deviceid":2}}}],"meta":{"count":1446,"next":1}}`

Cheers,
M&M

**Comment by perliedman** [comment]
Hi,
if you provide a function instead of an URL/reqwest options as the first argument when creating the layer, this function can do whatever you need to do to fetch the data and transform it into GeoJSON. See the docs here: https://github.com/perliedman/leaflet-realtime#-source

The (currently non-working) trains example use this technique to transform a custom data format into GeoJON: https://github.com/perliedman/leaflet-realtime/blob/master/examples/trains.js#L32

**Comment by m-menon** [comment]
hi,

Cool, thanks a lot. :+1:  Cheers
