### ISSUE TITLE
Number of lat-long positions which can be updated in a 1 second interval

### ISSUE THREAD

**Issue by sreekanth13** [perliedman/leaflet-realtime#31]
Hi,
 I want to know how many lat-long positions can be updated with one second time interval?
 When I tried around 300 points, it seems Chrome and Firefox are struggling in less than 4 minutes.
 Can you please suggest the safe no of positions

Thanks,
Sreekanth

**Comment by perliedman** [comment]
That's a very hard question to answer, since there are so many variables involved. Primarily it depends on:

* Bandwidth (how many positions can you fetch in a second?)
* Computer (CPU speed, graphics update speed, available memory)
* Browser (different browsers vary greatly in JavaScript performance)

Also, I haven't really load tested Leaflet Realtime with more than perhaps a hundred markers, so I really don't know.

#18 is a possible performance improvement, but I'm not in a position to take on implementing that myself at the moment.

**Comment by SegFault0x0** [comment]
@sreekanth13 I'm working with a hundred or so markers and my CPU wouldn't drop below 25%.  I created a class with the **will-change** CSS property and attached it to each new marker via the _classname_ option.
```css
.animatedMarker {
  /* Place marker on a separate layer for improved performance */
  will-change: transform;
}
```
```javascript
marker.setIcon(new L.Icon({
    iconUrl: iconImage.png,
    ...
    classname: 'animatedMarker',
}));
```
Chrome still occasionally manages to hover my CPU at around 30% (normally after moving about in the map), but there are times when it calms down and I see 0-5% with all of my markers in motion.
