### ISSUE TITLE
Publish array of points

### ISSUE THREAD

**Issue by fedegonzal** [perliedman/leaflet-realtime#35]
Hi, great tool! Thanks. I want to show a map with an array of points (not a multipoint geometry) because I need to show many properties for each point. It's possible? I could't find the way.

Example:
`var someFeatures = [{
    "type": "Feature",
    "properties": {
        "name": "Coors Field"
    },
    "geometry": {
        "type": "Point",
        "coordinates": [-105.35721, 40.25846]
    }
}, {
    "type": "Feature",
    "properties": {
        "name": "Busch Field"
    },
    "geometry": {
        "type": "Point",
        "coordinates": [-104.98404, 39.74621]
    }
}];
`

**Comment by perliedman** [comment]
Yes, definitely possible. This is the most common use case.

What you need to do is to provide a unique identifier for each feature, and tell Leaflet Realtime about it. Otherwise there's no way to tell which features are added, updated or removed between requests.

By default, Leaflet Realtime will use the property `id` on each feature to do this, but if you want to override it there's an option called `getFeatureId` which you can use. For example, if the `name` property in your example is guaranteed to be unique, you can do:

```javascript
var realtime = L.realtime('http://...', {
    getFeatureId: function(f) { return f.properties.name; }
});
```
