### ISSUE TITLE
live tracking GPS units

### ISSUE THREAD

**Issue by kirantpatil** [perliedman/leaflet-realtime#38]
Hello leaflet-realtime team,

I would like to track GPS units using leaflet-realtime. 

I have no idea how to push GPS location details to leaflet-realtime.

May I know the details of how to integrate GPS from mobile to leaflet-realtime ?

I thought of using https://www.traccar.org/.

Please educate me on this issue.

Thanks.

**Comment by perliedman** [comment]
You need to have some kind of backend to collect the coordinates of the units you want to track. I've seen traccar before, but never used it. You can use something like that, or probably a dozen similar solutions. For basic usage, it's pretty easy to write your own backend as well.

To use it with Leaflet Realtime, you need some way to get the coordinates from the backend to the client. If you can get it as GeoJSON, you're more or less good to go, otherwise you need to write a translator from your backend's format to GeoJSON; this is often also trivial, however.

Look at some of the examples to see how Leaflet Realtime can be used with different backends!
