### ISSUE TITLE
option for explicit lat/lon variables instead of querying external site/url

### ISSUE THREAD

**Issue by swordsteel** [perliedman/leaflet-realtime#5]
Would be useful to have the option to switch between
 
url: 'https://wanderdrone.appspot.com/'
and
[$lat,$lon]  or something in this vein. Point in case is where the user has already retreived lat/lon serverside, and wants leaflet-realtime to use these local values instead of querying an external site.

**Comment by swordsteel** [comment]
I have geo.php in a subfolder off root at http://my-url/gps/geo.php

Code I am using is as follows:
```
<?php
$date = $lat = $lon = '';

$date_lat_lon = rtrim(file_get_contents("/gps/gps-position.txt"));
if ($date_lat_lon) {
	list($date, $lat, $lon) = explode("_", $date_lat_lon);
}

echo '{"geometry": {"type": "Point", "coordinates": [' . $lat . ', ' . $lon . ']}, "type": "Feature", "properties": {}}';
?>
```

Then the only line modified in index.js is

```
url: 'http://my-url/gps/geo.php',
```

When I point index.js to http://my-url/gps/geo.php the marker centers in the middle of the screen and does not align to the value taken from the file.

If I visit the url I get an identical string format viewed on the page with correct coords the same as when visiting https://wanderdrone.appspot.com/

**Comment by perliedman** [comment]
I think what you need is already in Leaflet Realtime. Instead of providing a URL, you can pass a function instead. This function will be called when the layer is updated, with two callbacks as arguments: `success` and `error`.

This way, you can perform any operation you need to get updated data, even asynchronous operations.

Look at the docs for about [source](https://github.com/perliedman/leaflet-realtime#-source) for more details.
