### ISSUE TITLE
Encoded GeoJSON

### ISSUE THREAD

**Issue by rtfmfm** [perliedman/leaflet-realtime#54]
Hello Sir!
Are you going to support encoded GeoJSON? It's about 10 times smaller than regular GeoJSON and there is a huge difference while the json data is larger (>1MB).

Reference: https://developers.google.com/maps/documentation/utilities/polylinealgorithm

Best regards!

**Comment by perliedman** [comment]
Hi,

since Leaflet Realtime is just an extension of Leaflet's GeoJSON functionality, it depends on if Leaflet supports it. I'm guessing it's not something that will be added to Leaflet any time soon, though, since it's mostly a matter of decoding the encoded data before passing it to Leaflet.

For Leaflet Realtime, you can easily use encoded GeoJSON, or any other data format, by using a [source](https://github.com/perliedman/leaflet-realtime#-source) that is a function, and make that function decode the data to GeoJSON.
