### ISSUE TITLE
How to convert from ordinary Json with lat and long data to geocode

### ISSUE THREAD

**Issue by bilalbayasut** [perliedman/leaflet-realtime#66]
Hi I have an api that return json data, so how can I use this plugin? Thanks

**Comment by perliedman** [comment]
Hi!

As mentioned in the [docs for sources](https://github.com/perliedman/leaflet-realtime#-source), supply a function instead of a URL configuration, you can manage polling and transforming the result yourself.

This means that you will have to write a custom function that fetches your JSON data, and then transform the data into GeoJSON that Leaflet Realtime can understand.

Note that this is an asynchronous process, so you will have to call the provided success callback with the transformed data yourself.

**Comment by bilalbayasut** [comment]
Okay, so it means that I have to add extra layer process for transforming the json into Geojson ? 

I though there already a function exist just to do that, thanks @perliedman

**Comment by perliedman** [comment]
No, JSON is an extremely general format, there's nothing in "ordinary JSON" that says anything about how latitudes and longitudes are expressed, or anything about geographic information at all, for that matter. So, given that you have arbitrary JSON, you need to do the transformation to GeoJSON yourself.
