### ISSUE TITLE
leaflet-realtime in angular2 project

### ISSUE THREAD

**Issue by hlherrera** [perliedman/leaflet-realtime#70]
How to use realtime plugin in angular2(angular-cli) project?

**Comment by perliedman** [comment]
Hi,
sorry to say that I have no Angular 2 experience, so it's hard to give any advice. For Angular 1, I would probably go for implementing a realtime layer as a directive, but it depends on the structure of the rest of your app, so it's hard to say anything general. Since Leaflet Realtime is just another type of layer, wrap it like you would with other layers.

Anyway, integration with other frameworks is a bit outside the scope of the issue tracker, so I'm going to close this.
