### ISSUE TITLE
Tooltip and Popup Move to location then Marker catches up as it is animated

### ISSUE THREAD

**Issue by wicadmin** [perliedman/leaflet-realtime#82]
First, thanks for this add-on. The only issue I am currently facing is that open popup and permanent tooltip on a marker doesn't move to new coordinates animatedly with the marker. They go to the new location then the marker catches up as it is an animated move. How can I get the popup and tooltip to always stay with the marker and also move with it animatedly?

Using some changes from [here](https://stackoverflow.com/questions/42001003/leaflet-tooltip-wont-animate-correctly) makes it work as expected on first load. But subsequent updates to new coordinates has the original behavior described above.

**Comment by perliedman** [comment]
Hi, thanks for using Leaflet Realtime!

Hard to tell without seeing it in action. I would have suggested adding `transition` properties for the tooltip/popup, but it sounds like you've already tried that, but I'm not sure why it only works the first time.

If you could put an example online, I might be able to debug it, but otherwise it's hard for me to say without more details.

**Comment by 2devnull** [comment]
I'll try to put something together but if you look at the wanderdrone example you have and you keep the popup open, you'll see that the popup first moves the the new coordinates then the marker follows. When the animation of the marker move is slower this issue is more pronounced. How to get the popup/tooltip to always move with the marker at the marker speed?

**Comment by perliedman** [comment]
Excellent, that's a good way to reproduce it! I'll try to have a look as soon as possible, but can't promise anything unfortunately.

**Comment by perliedman** [comment]
Looking at this again, it is quite clear to me that this is how Leaflet works, rather than an issue with Leaflet Realtime.

I guess it could be solved by introducing a CSS transition on Leaflet's popup (which is how the smooth marker movement works), but since that code is in Leaflet, it's outside the plugin's scope.

Feel free to drop a comment if you fixed this and tell us how!
